# Generated by Django 4.1.2 on 2022-10-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=50)),
                ('data_nascimento', models.CharField(max_length=50)),
                ('criado_em', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
